language: node_js
node_js:
  - 10.15.3
branches:
  only:
    - master
install:
  - npm install
before_install:
  - openssl aes-256-cbc -K $encrypted_87e12e88f71d_key -iv $encrypted_87e12e88f71d_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts:
    - 47.100.18.197

after_success:
  - ssh travis@47.100.18.197 -o StrictHostKeyChecking=no "./bin/shell"
